package br.senai.sc.ajudeaqui.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle.ComponentPlacement;

import br.senai.sc.ajudeaqui.abstracts.Entidade;
import br.senai.sc.ajudeaqui.controller.VoluntarioAnuncioController;
import br.senai.sc.ajudeaqui.controller.VoluntarioController;
import br.senai.sc.ajudeaqui.model.Anuncio;
import br.senai.sc.ajudeaqui.model.Instituicao;
import br.senai.sc.ajudeaqui.model.Voluntario;
import br.senai.sc.ajudeaqui.model.VoluntarioAnuncio;
import br.senai.sc.ajudeaqui.utils.StringUtils;

/**
 * Classe que contém a tela de visualização dos dados do anúncio.
 * 
 * @author Jaime Gomes
 *
 */
public class AnuncioUI extends javax.swing.JInternalFrame {

	private static final long serialVersionUID = 1L;
	private javax.swing.JButton btnFechar;
	private javax.swing.JLabel lblTitulo;
	private javax.swing.JPanel panelAnuncio;
	private JLabel lblVagas;
	private JLabel lblQtdVagas;
	private JLabel lblTipoDeServio;
	private JLabel lblTipoServicoDinamico;
	private JLabel lblDescricao;
	private JLabel lblDescricaoDinamica;
	private JLabel lblDataDePublicacao;
	private JLabel lblDataPublicacaoDinamica;
	private JButton btnDinamico;

	private VoluntarioAnuncioController voluntarioAnuncioController = new VoluntarioAnuncioController();

	/**
	 * Creates new form RelatorioUI
	 */
	public AnuncioUI(Anuncio anuncio, Entidade ent) {
		initComponents(anuncio, ent);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	private void initComponents(final Anuncio anuncio, Entidade ent) {

		panelAnuncio = new javax.swing.JPanel();
		lblTitulo = new javax.swing.JLabel(anuncio.getTitulo());
		btnFechar = new javax.swing.JButton();
		lblVagas = new JLabel("Vagas:");
		lblQtdVagas = new JLabel("" + anuncio.getQtdVagas());
		lblTipoDeServio = new JLabel("Tipo de Servi\u00E7o:");
		lblTipoServicoDinamico = new JLabel(anuncio.getFuncao().getFuncao());
		lblDescricao = new JLabel("Descri\u00E7\u00E3o:");
		lblDescricaoDinamica = new JLabel(anuncio.getDescricao());
		lblDataDePublicacao = new JLabel("Data de Publica\u00E7\u00E3o:");
		try {
			lblDataPublicacaoDinamica = new JLabel(
					StringUtils.getInstance().parseDateToString(anuncio.getDataPublicacao()));
		} catch (ParseException e) {
			e.printStackTrace();
		}
		btnFechar.setIcon(new javax.swing.ImageIcon("img/cancelar_16x16.png")); // NOI18N
		btnFechar.setText("Fechar");
		btnFechar.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				dispose();

			}
		});

		btnDinamico = new JButton();
		btnDinamico.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
			}
		});
		if (ent instanceof Instituicao) {
			btnDinamico.setText("Candidatos a vaga");
			btnDinamico.setIcon(new javax.swing.ImageIcon("img/usuario_16x16.png"));

			btnDinamico.addActionListener(new ActionListener() {

				@Override
				public void actionPerformed(ActionEvent e) {

					try {
						VoluntarioController volController = new VoluntarioController();
						List<Entidade> list = voluntarioAnuncioController.getPorIdAnuncio(anuncio.getId());
						List<Entidade> listVoluntarios = new ArrayList<Entidade>();

						for (Entidade en : list) {

							VoluntarioAnuncio voluntarioAnuncio = (VoluntarioAnuncio) en;

							Voluntario vol = (Voluntario) volController.getPorId(voluntarioAnuncio.getIdVoluntario());
							listVoluntarios.add(vol);

						}

						if (listVoluntarios.size() > 0) {
							dispose();
							CandidatosVagaUI volUI = new CandidatosVagaUI(listVoluntarios, anuncio);
							volUI.setFocusable(true);
							volUI.setVisible(true);

						} else {
							JOptionPane.showMessageDialog(null, "Não existem candidatos para este anúncio.");
						}

					} catch (Exception e1) {
						e1.printStackTrace();
					}

				}
			});

		} else if (ent instanceof Voluntario) {

			final Voluntario vol = (Voluntario) ent;

			btnDinamico.setText("Candidatar-se");
			btnDinamico.setIcon(new javax.swing.ImageIcon("img/add_16x16.png"));
			btnDinamico.addActionListener(new ActionListener() {

				@Override
				public void actionPerformed(ActionEvent e) {

					try {

						if (anuncio.getStatus().equals("Aberto")) {
							List<Entidade> list = voluntarioAnuncioController.getPorIdVoluntarioIdAnuncio(vol.getId(),
									anuncio.getId());

							if (list != null) {
								JOptionPane.showMessageDialog(null,
										"Você já está inscrito para esta vaga, aguarde contato da instituição e mantenha seu perfil atualizado.");
							} else {
								VoluntarioAnuncio voluntarioAnuncio = new VoluntarioAnuncio(vol.getId(),
										anuncio.getId());

								voluntarioAnuncioController.salvar(voluntarioAnuncio);
								JOptionPane.showMessageDialog(null,
										"Você se inscreveu para esta vaga, aguarde contato da instituição e mantenha seu perfil atualizado.");
							}
						}

					} catch (Exception e1) {
						e1.printStackTrace();
					}

				}
			});
		} else if (ent == null) {
			btnDinamico.setVisible(false);
		}

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle(":: Sistema do Voluntário Ajude Aqui ::");

		lblTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
		lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

		javax.swing.GroupLayout gl_panelAnuncio = new javax.swing.GroupLayout(panelAnuncio);
		gl_panelAnuncio.setHorizontalGroup(gl_panelAnuncio.createParallelGroup(Alignment.LEADING)
				.addComponent(lblTitulo, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
				.addGroup(gl_panelAnuncio.createSequentialGroup().addContainerGap().addComponent(lblVagas)
						.addPreferredGap(ComponentPlacement.RELATED).addComponent(lblQtdVagas)
						.addContainerGap(854, Short.MAX_VALUE))
				.addGroup(gl_panelAnuncio.createSequentialGroup().addContainerGap().addComponent(lblTipoDeServio)
						.addPreferredGap(ComponentPlacement.RELATED).addComponent(lblTipoServicoDinamico)
						.addContainerGap(721, Short.MAX_VALUE))
				.addGroup(gl_panelAnuncio.createSequentialGroup().addContainerGap().addComponent(lblDescricao)
						.addPreferredGap(ComponentPlacement.RELATED).addComponent(lblDescricaoDinamica)
						.addContainerGap(759, Short.MAX_VALUE))
				.addGroup(gl_panelAnuncio.createSequentialGroup().addContainerGap().addComponent(lblDataDePublicacao)
						.addPreferredGap(ComponentPlacement.RELATED).addComponent(lblDataPublicacaoDinamica)
						.addContainerGap(692, Short.MAX_VALUE)));
		gl_panelAnuncio
				.setVerticalGroup(
						gl_panelAnuncio.createParallelGroup(Alignment.LEADING)
								.addGroup(gl_panelAnuncio.createSequentialGroup()
										.addComponent(lblTitulo, GroupLayout.PREFERRED_SIZE, 73,
												GroupLayout.PREFERRED_SIZE)
										.addGap(53)
										.addGroup(gl_panelAnuncio.createParallelGroup(Alignment.BASELINE)
												.addComponent(lblVagas).addComponent(lblQtdVagas))
				.addPreferredGap(ComponentPlacement.UNRELATED)
				.addGroup(gl_panelAnuncio.createParallelGroup(Alignment.BASELINE).addComponent(lblTipoDeServio)
						.addComponent(lblTipoServicoDinamico))
				.addGap(11)
				.addGroup(gl_panelAnuncio.createParallelGroup(Alignment.BASELINE).addComponent(lblDataDePublicacao)
						.addComponent(lblDataPublicacaoDinamica)).addPreferredGap(ComponentPlacement.UNRELATED)
				.addGroup(gl_panelAnuncio.createParallelGroup(Alignment.BASELINE).addComponent(lblDescricao)
						.addComponent(lblDescricaoDinamica)).addGap(292)));
		panelAnuncio.setLayout(gl_panelAnuncio);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(panelAnuncio, GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
								.addGroup(layout.createSequentialGroup()
										.addComponent(btnDinamico, GroupLayout.PREFERRED_SIZE, 222,
												GroupLayout.PREFERRED_SIZE)
										.addGap(18).addComponent(btnFechar, GroupLayout.PREFERRED_SIZE, 115,
												GroupLayout.PREFERRED_SIZE)))
						.addContainerGap()));
		layout.setVerticalGroup(
				layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addContainerGap()
								.addComponent(panelAnuncio, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(Alignment.TRAILING)
										.addComponent(btnFechar, GroupLayout.PREFERRED_SIZE, 19,
												GroupLayout.PREFERRED_SIZE)
								.addComponent(btnDinamico, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE))
				.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>
}
