package br.senai.sc.ajudeaqui.view;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.LayoutStyle.ComponentPlacement;

import br.senai.sc.ajudeaqui.abstracts.Entidade;
import br.senai.sc.ajudeaqui.controller.AnuncioController;
import br.senai.sc.ajudeaqui.model.Anuncio;
import br.senai.sc.ajudeaqui.tablemodel.AnuncioTableModel;

public class CandidaturasUI extends javax.swing.JInternalFrame {

	private static final long serialVersionUID = 1L;
	private javax.swing.JButton btnFechar;
	private javax.swing.JLabel lblTitulo;
	private javax.swing.JPanel panelVoluntario;
	private JTable table;

	/**
	 * Creates new form RelatorioUI
	 */
	public CandidaturasUI(List<Entidade> listAnuncios) {
		initComponents(listAnuncios);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	private void initComponents(List<Entidade> listAnuncios) {

		panelVoluntario = new javax.swing.JPanel();
		lblTitulo = new javax.swing.JLabel("Candidaturas");
		btnFechar = new javax.swing.JButton();
		btnFechar.setIcon(new javax.swing.ImageIcon("img/cancelar_16x16.png")); // NOI18N
		btnFechar.setText("Fechar");
		btnFechar.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {

				dispose();
			}

		});

		setTitle(":: Sistema do Voluntário Ajude Aqui ::");

		lblTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
		lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

		JScrollPane scrollPane = new JScrollPane();
		scrollPane.setPreferredSize(new Dimension(1197, 520));
		scrollPane.setMinimumSize(new Dimension(1197, 520));
		scrollPane.setMaximumSize(new Dimension(1197, 520));

		javax.swing.GroupLayout gl_panelVoluntario = new javax.swing.GroupLayout(
				panelVoluntario);
		gl_panelVoluntario.setHorizontalGroup(gl_panelVoluntario
				.createParallelGroup(Alignment.LEADING)
				.addComponent(lblTitulo, Alignment.TRAILING,
						GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)
				.addGroup(
						gl_panelVoluntario
								.createSequentialGroup()
								.addContainerGap()
								.addComponent(scrollPane,
										GroupLayout.PREFERRED_SIZE, 1197,
										GroupLayout.PREFERRED_SIZE)
								.addContainerGap(GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		gl_panelVoluntario.setVerticalGroup(gl_panelVoluntario
				.createParallelGroup(Alignment.LEADING).addGroup(
						gl_panelVoluntario
								.createSequentialGroup()
								.addComponent(lblTitulo,
										GroupLayout.PREFERRED_SIZE, 73,
										GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.RELATED,
										28, Short.MAX_VALUE)
								.addComponent(scrollPane,
										GroupLayout.PREFERRED_SIZE, 520,
										GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));

		table = new JTable();
		table.setPreferredSize(new Dimension(1197, 520));
		table.setMinimumSize(new Dimension(1197, 520));
		table.setMaximumSize(new Dimension(1197, 520));
		table.setAutoscrolls(false);
		table.setModel(new AnuncioTableModel(listAnuncios));
		table.addMouseListener(new MouseAdapter() {

			@Override
			public void mouseClicked(MouseEvent e) {
				if (e.getClickCount() == 2) {

					int linhaSelecionada = table.getSelectedRow();

					int idAnuncio = Integer.parseInt(table.getValueAt(
							linhaSelecionada, 0).toString());

					AnuncioController anuncioController = new AnuncioController();

					Anuncio anuncio = null;
					try {
						anuncio = (Anuncio) anuncioController
								.getPorId(idAnuncio);
					} catch (Exception e1) {
						e1.printStackTrace();
					}

					AnuncioUI anuncioUI = new AnuncioUI(anuncio, null);
					anuncioUI.setFocusable(true);
					anuncioUI.moveToFront();
					getContentPane().add(anuncioUI, 0);
					anuncioUI.setVisible(true);
				}
			}
		});

		scrollPane.setViewportView(table);

		panelVoluntario.setLayout(gl_panelVoluntario);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(layout
				.createParallelGroup(Alignment.TRAILING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		panelVoluntario,
																		GroupLayout.DEFAULT_SIZE,
																		GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addContainerGap())
												.addGroup(
														Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		btnFechar,
																		GroupLayout.PREFERRED_SIZE,
																		110,
																		GroupLayout.PREFERRED_SIZE)
																.addGap(24)))));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(panelVoluntario,
										GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.UNRELATED)
								.addComponent(btnFechar,
										GroupLayout.PREFERRED_SIZE, 19,
										GroupLayout.PREFERRED_SIZE)
								.addContainerGap(GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>
}
