/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.sc.ajudeaqui.view;

/**
 *
 * @author Jaime Gomes
 */
public class PrincipalInstituicaoUI extends javax.swing.JFrame {
	
	private static final long serialVersionUID = 1L;

    /**
     * Creates new form PrincipalInstituicaoUI
     */
    public PrincipalInstituicaoUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        menuPrincipalInstituicao = new javax.swing.JTabbedPane();
        panelInstituicao = new javax.swing.JPanel();
        panelDadosInstituicao = new javax.swing.JPanel();
        btnSalvarDadosInstituicao = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        txtCnpj = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        lblRazaoSocial = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblCnpj = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtSite = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblObservacoes = new javax.swing.JLabel();
        lblResponsavel = new javax.swing.JLabel();
        scrollpaneObservacoes = new javax.swing.JScrollPane();
        atxtObservacoes = new javax.swing.JTextArea();
        txtTelefone = new javax.swing.JTextField();
        txtRazaoSocial = new javax.swing.JTextField();
        lblSite = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtResponsavel = new javax.swing.JTextField();
        btnEditarDadosInstituicao1 = new javax.swing.JButton();
        panelVoluntarios = new javax.swing.JPanel();
        panelFiltroVoluntarios = new javax.swing.JPanel();
        lblNomeFiltroVoluntarios = new javax.swing.JLabel();
        lblEmailFiltroVoluntarios = new javax.swing.JLabel();
        txtNomeFiltroVoluntarios = new javax.swing.JTextField();
        txtEmailFiltroVoluntarios = new javax.swing.JTextField();
        btnPesquisarFiltroVoluntarios = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        btnFiltroVoluntarios = new javax.swing.JButton();
        scrollpaneVoluntarios = new javax.swing.JScrollPane();
        tableVoluntarios = new javax.swing.JTable();
        panelAviso = new javax.swing.JPanel();
        panelCadAviso = new javax.swing.JPanel();
        lblTituloCadAviso = new javax.swing.JLabel();
        txtTituloCadAviso = new javax.swing.JTextField();
        lblDescricaoCadAviso = new javax.swing.JLabel();
        scrollpaneDescricaoCadAviso = new javax.swing.JScrollPane();
        atxtDescricaoCadAviso = new javax.swing.JTextArea();
        btnSalvarAvisoCadAviso = new javax.swing.JButton();
        lblTipoServicoAviso = new javax.swing.JLabel();
        cmbTipoServicoAviso = new javax.swing.JComboBox();
        panelAvisosPublicados = new javax.swing.JPanel();
        scrollpaneAvisosPublicados = new javax.swing.JScrollPane();
        tableAvisosPublicados = new javax.swing.JTable();
        lblFiltroTituloAvisosPublicados = new javax.swing.JLabel();
        txtFiltroTituloAvisosPublicados = new javax.swing.JTextField();
        btnPesquisarAvisosPublicados = new javax.swing.JButton();
        btnEditarAviso = new javax.swing.JButton();
        btnExcluirAviso = new javax.swing.JButton();
        panelAnuncio = new javax.swing.JPanel();
        panelAnunciosPublicados = new javax.swing.JPanel();
        scrollpaneAnunciosPublicados = new javax.swing.JScrollPane();
        tableAnunciosPublicados = new javax.swing.JTable();
        btnPesquisarAnunciosPublicados = new javax.swing.JButton();
        lblFiltroTituloAnunciosPublicados = new javax.swing.JLabel();
        txtFiltroTituloAnunciosPublicados = new javax.swing.JTextField();
        btnEditarAnuncio = new javax.swing.JButton();
        btnExcluirAnuncio = new javax.swing.JButton();
        btnFiltroVoluntarios1 = new javax.swing.JButton();
        panelCadAnuncio = new javax.swing.JPanel();
        lblTituloCadAnuncio = new javax.swing.JLabel();
        spinnerVagasCadAnuncio = new javax.swing.JSpinner();
        lblVagasCadAnuncio = new javax.swing.JLabel();
        txtTituloCadAnuncio = new javax.swing.JTextField();
        lblDescricaoCadAnuncio = new javax.swing.JLabel();
        scrollpaneDescricaoCadAnuncio = new javax.swing.JScrollPane();
        atxtDescricaoCadAnuncio = new javax.swing.JTextArea();
        btnSalvarCadAnuncio = new javax.swing.JButton();
        lblTipoServicoAnuncio = new javax.swing.JLabel();
        cmbTipoServicoAnuncio = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(":: Sistema doVoluntário Ajude Aqui ::");
        setMaximumSize(new java.awt.Dimension(1300, 700));
        setMinimumSize(new java.awt.Dimension(1300, 700));
        setName("frameInstituicao"); // NOI18N

        menuPrincipalInstituicao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuPrincipalInstituicao.setMaximumSize(new java.awt.Dimension(1300, 700));
        menuPrincipalInstituicao.setMinimumSize(new java.awt.Dimension(1300, 700));
        menuPrincipalInstituicao.setPreferredSize(new java.awt.Dimension(1300, 700));

        panelInstituicao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelInstituicao.setMaximumSize(new java.awt.Dimension(1110, 700));
        panelInstituicao.setMinimumSize(new java.awt.Dimension(1110, 700));
        panelInstituicao.setPreferredSize(new java.awt.Dimension(1110, 700));

        panelDadosInstituicao.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Instituição"));

        btnSalvarDadosInstituicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salvar_16x16.png"))); // NOI18N
        btnSalvarDadosInstituicao.setText("Salvar");

        lblRazaoSocial.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblRazaoSocial.setText("Razão Social:");

        lblTelefone.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblTelefone.setText("Telefone:");

        lblEndereco.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblEndereco.setText("Endereço:");

        lblCnpj.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblCnpj.setText("CNPJ:");

        lblEmail.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblEmail.setText("Email:");

        lblObservacoes.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblObservacoes.setText("Observações:");

        lblResponsavel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblResponsavel.setText("Responsável:");

        atxtObservacoes.setColumns(20);
        atxtObservacoes.setRows(5);
        scrollpaneObservacoes.setViewportView(atxtObservacoes);

        lblSite.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblSite.setText("Site:");

        lblNome.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblNome.setText("Nome:");

        btnEditarDadosInstituicao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar_usuario_16x16.png"))); // NOI18N
        btnEditarDadosInstituicao1.setText("Editar");

        javax.swing.GroupLayout panelDadosInstituicaoLayout = new javax.swing.GroupLayout(panelDadosInstituicao);
        panelDadosInstituicao.setLayout(panelDadosInstituicaoLayout);
        panelDadosInstituicaoLayout.setHorizontalGroup(
            panelDadosInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosInstituicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDadosInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDadosInstituicaoLayout.createSequentialGroup()
                        .addGroup(panelDadosInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDadosInstituicaoLayout.createSequentialGroup()
                                .addComponent(btnEditarDadosInstituicao1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSalvarDadosInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCnpj)
                            .addComponent(lblEmail)
                            .addGroup(panelDadosInstituicaoLayout.createSequentialGroup()
                                .addGroup(panelDadosInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNome)
                                    .addComponent(lblEndereco)
                                    .addComponent(lblSite)
                                    .addComponent(lblResponsavel)
                                    .addComponent(lblTelefone)
                                    .addComponent(lblRazaoSocial))
                                .addGap(19, 19, 19)
                                .addGroup(panelDadosInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSite, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelDadosInstituicaoLayout.createSequentialGroup()
                        .addComponent(lblObservacoes)
                        .addGap(18, 18, 18)
                        .addComponent(scrollpaneObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(371, 371, 371))))
        );
        panelDadosInstituicaoLayout.setVerticalGroup(
            panelDadosInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosInstituicaoLayout.createSequentialGroup()
                .addGroup(panelDadosInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDadosInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRazaoSocial)
                    .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDadosInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCnpj)
                    .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDadosInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDadosInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDadosInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEndereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDadosInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSite)
                    .addComponent(txtSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDadosInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResponsavel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDadosInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblObservacoes)
                    .addComponent(scrollpaneObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDadosInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarDadosInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarDadosInstituicao1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelInstituicaoLayout = new javax.swing.GroupLayout(panelInstituicao);
        panelInstituicao.setLayout(panelInstituicaoLayout);
        panelInstituicaoLayout.setHorizontalGroup(
            panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInstituicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDadosInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(734, Short.MAX_VALUE))
        );
        panelInstituicaoLayout.setVerticalGroup(
            panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInstituicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDadosInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(259, Short.MAX_VALUE))
        );

        menuPrincipalInstituicao.addTab("Instituição", new javax.swing.ImageIcon(getClass().getResource("/img/home_16x16.png.png")), panelInstituicao); // NOI18N

        panelVoluntarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelVoluntarios.setMaximumSize(new java.awt.Dimension(1110, 700));
        panelVoluntarios.setMinimumSize(new java.awt.Dimension(1110, 700));
        panelVoluntarios.setPreferredSize(new java.awt.Dimension(1110, 700));

        panelFiltroVoluntarios.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtro de Pesquisa"));
        panelFiltroVoluntarios.setMaximumSize(new java.awt.Dimension(1197, 115));
        panelFiltroVoluntarios.setMinimumSize(new java.awt.Dimension(1197, 115));
        panelFiltroVoluntarios.setPreferredSize(new java.awt.Dimension(1197, 115));

        lblNomeFiltroVoluntarios.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblNomeFiltroVoluntarios.setText("Nome:");

        lblEmailFiltroVoluntarios.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblEmailFiltroVoluntarios.setText("Email:");

        btnPesquisarFiltroVoluntarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa_16x16.png"))); // NOI18N
        btnPesquisarFiltroVoluntarios.setText("Pesquisar");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Tipo de Serviço:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnFiltroVoluntarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agenda_16x16.png"))); // NOI18N
        btnFiltroVoluntarios.setText("Gerar Relatório");

        javax.swing.GroupLayout panelFiltroVoluntariosLayout = new javax.swing.GroupLayout(panelFiltroVoluntarios);
        panelFiltroVoluntarios.setLayout(panelFiltroVoluntariosLayout);
        panelFiltroVoluntariosLayout.setHorizontalGroup(
            panelFiltroVoluntariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltroVoluntariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFiltroVoluntariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lblNomeFiltroVoluntarios)
                    .addComponent(lblEmailFiltroVoluntarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltroVoluntariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNomeFiltroVoluntarios, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEmailFiltroVoluntarios, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox2, 0, 258, Short.MAX_VALUE))
                .addGroup(panelFiltroVoluntariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFiltroVoluntariosLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnPesquisarFiltroVoluntarios)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFiltroVoluntariosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFiltroVoluntarios)
                        .addContainerGap())))
        );
        panelFiltroVoluntariosLayout.setVerticalGroup(
            panelFiltroVoluntariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltroVoluntariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFiltroVoluntariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFiltroVoluntariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNomeFiltroVoluntarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPesquisarFiltroVoluntarios, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNomeFiltroVoluntarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltroVoluntariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailFiltroVoluntarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailFiltroVoluntarios))
                .addGap(7, 7, 7)
                .addGroup(panelFiltroVoluntariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFiltroVoluntariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFiltroVoluntarios, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scrollpaneVoluntarios.setMaximumSize(new java.awt.Dimension(1197, 520));
        scrollpaneVoluntarios.setMinimumSize(new java.awt.Dimension(1197, 520));
        scrollpaneVoluntarios.setPreferredSize(new java.awt.Dimension(1197, 520));

        tableVoluntarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Data Nascimento", "Endereço", "Celular", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableVoluntarios.setAutoscrolls(false);
        tableVoluntarios.setMaximumSize(new java.awt.Dimension(1197, 520));
        tableVoluntarios.setMinimumSize(new java.awt.Dimension(1197, 520));
        tableVoluntarios.setPreferredSize(new java.awt.Dimension(1197, 520));
        scrollpaneVoluntarios.setViewportView(tableVoluntarios);

        javax.swing.GroupLayout panelVoluntariosLayout = new javax.swing.GroupLayout(panelVoluntarios);
        panelVoluntarios.setLayout(panelVoluntariosLayout);
        panelVoluntariosLayout.setHorizontalGroup(
            panelVoluntariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVoluntariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVoluntariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollpaneVoluntarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelFiltroVoluntarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        panelVoluntariosLayout.setVerticalGroup(
            panelVoluntariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVoluntariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFiltroVoluntarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollpaneVoluntarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        menuPrincipalInstituicao.addTab("Voluntários", new javax.swing.ImageIcon(getClass().getResource("/img/usuarios_16x16.png")), panelVoluntarios); // NOI18N

        panelAviso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelAviso.setMaximumSize(new java.awt.Dimension(1110, 700));
        panelAviso.setMinimumSize(new java.awt.Dimension(1110, 700));
        panelAviso.setPreferredSize(new java.awt.Dimension(1110, 700));

        panelCadAviso.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Avisos"));
        panelCadAviso.setMaximumSize(new java.awt.Dimension(1197, 222));
        panelCadAviso.setMinimumSize(new java.awt.Dimension(1197, 222));
        panelCadAviso.setPreferredSize(new java.awt.Dimension(1197, 222));

        lblTituloCadAviso.setText("Título:");

        lblDescricaoCadAviso.setText("Descrição:");

        atxtDescricaoCadAviso.setColumns(20);
        atxtDescricaoCadAviso.setRows(5);
        scrollpaneDescricaoCadAviso.setViewportView(atxtDescricaoCadAviso);

        btnSalvarAvisoCadAviso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salvar_16x16.png"))); // NOI18N
        btnSalvarAvisoCadAviso.setText("Salvar");

        lblTipoServicoAviso.setText("Tipo de Serviço:");

        cmbTipoServicoAviso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelCadAvisoLayout = new javax.swing.GroupLayout(panelCadAviso);
        panelCadAviso.setLayout(panelCadAvisoLayout);
        panelCadAvisoLayout.setHorizontalGroup(
            panelCadAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadAvisoLayout.createSequentialGroup()
                .addGroup(panelCadAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadAvisoLayout.createSequentialGroup()
                        .addComponent(lblTituloCadAviso)
                        .addGap(51, 51, 51)
                        .addComponent(txtTituloCadAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCadAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSalvarAvisoCadAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelCadAvisoLayout.createSequentialGroup()
                            .addGroup(panelCadAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadAvisoLayout.createSequentialGroup()
                                    .addComponent(lblTipoServicoAviso)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(panelCadAvisoLayout.createSequentialGroup()
                                    .addComponent(lblDescricaoCadAviso)
                                    .addGap(31, 31, 31)))
                            .addGroup(panelCadAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(scrollpaneDescricaoCadAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbTipoServicoAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCadAvisoLayout.setVerticalGroup(
            panelCadAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadAvisoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloCadAviso)
                    .addComponent(txtTituloCadAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCadAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbTipoServicoAviso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoServicoAviso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCadAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescricaoCadAviso)
                    .addComponent(scrollpaneDescricaoCadAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvarAvisoCadAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelAvisosPublicados.setBorder(javax.swing.BorderFactory.createTitledBorder("Avisos Publicados"));
        panelAvisosPublicados.setMaximumSize(new java.awt.Dimension(1197, 417));
        panelAvisosPublicados.setMinimumSize(new java.awt.Dimension(1197, 417));

        scrollpaneAvisosPublicados.setMaximumSize(new java.awt.Dimension(1197, 367));
        scrollpaneAvisosPublicados.setMinimumSize(new java.awt.Dimension(1197, 367));
        scrollpaneAvisosPublicados.setPreferredSize(new java.awt.Dimension(1197, 367));

        tableAvisosPublicados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableAvisosPublicados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título", "Descrição", "Data Publicação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableAvisosPublicados.setMaximumSize(new java.awt.Dimension(1197, 367));
        tableAvisosPublicados.setMinimumSize(new java.awt.Dimension(1197, 367));
        tableAvisosPublicados.setPreferredSize(new java.awt.Dimension(1197, 367));
        tableAvisosPublicados.setRowHeight(30);
        scrollpaneAvisosPublicados.setViewportView(tableAvisosPublicados);

        lblFiltroTituloAvisosPublicados.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblFiltroTituloAvisosPublicados.setText("Título:");

        btnPesquisarAvisosPublicados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa_16x16.png"))); // NOI18N
        btnPesquisarAvisosPublicados.setText("Pesquisar");

        btnEditarAviso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar_usuario_16x16.png"))); // NOI18N
        btnEditarAviso.setText("Editar");

        btnExcluirAviso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar_16x16.png"))); // NOI18N
        btnExcluirAviso.setText("Excluir");

        javax.swing.GroupLayout panelAvisosPublicadosLayout = new javax.swing.GroupLayout(panelAvisosPublicados);
        panelAvisosPublicados.setLayout(panelAvisosPublicadosLayout);
        panelAvisosPublicadosLayout.setHorizontalGroup(
            panelAvisosPublicadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAvisosPublicadosLayout.createSequentialGroup()
                .addComponent(lblFiltroTituloAvisosPublicados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFiltroTituloAvisosPublicados, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisarAvisosPublicados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditarAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluirAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(scrollpaneAvisosPublicados, javax.swing.GroupLayout.PREFERRED_SIZE, 1187, Short.MAX_VALUE)
        );
        panelAvisosPublicadosLayout.setVerticalGroup(
            panelAvisosPublicadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAvisosPublicadosLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(panelAvisosPublicadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFiltroTituloAvisosPublicados)
                    .addComponent(txtFiltroTituloAvisosPublicados, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarAvisosPublicados, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollpaneAvisosPublicados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelAvisoLayout = new javax.swing.GroupLayout(panelAviso);
        panelAviso.setLayout(panelAvisoLayout);
        panelAvisoLayout.setHorizontalGroup(
            panelAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAvisoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelAvisosPublicados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCadAviso, javax.swing.GroupLayout.DEFAULT_SIZE, 1199, Short.MAX_VALUE))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        panelAvisoLayout.setVerticalGroup(
            panelAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAvisoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCadAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAvisosPublicados, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        menuPrincipalInstituicao.addTab("Aviso", new javax.swing.ImageIcon(getClass().getResource("/img/journal_16x16.png")), panelAviso); // NOI18N

        panelAnuncio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelAnuncio.setMaximumSize(new java.awt.Dimension(1110, 700));
        panelAnuncio.setMinimumSize(new java.awt.Dimension(1110, 700));
        panelAnuncio.setPreferredSize(new java.awt.Dimension(1110, 700));
        panelAnuncio.setRequestFocusEnabled(false);

        panelAnunciosPublicados.setBorder(javax.swing.BorderFactory.createTitledBorder("Anúncios Publicados"));
        panelAnunciosPublicados.setMaximumSize(new java.awt.Dimension(1197, 399));
        panelAnunciosPublicados.setMinimumSize(new java.awt.Dimension(1197, 399));
        panelAnunciosPublicados.setPreferredSize(new java.awt.Dimension(1197, 399));

        scrollpaneAnunciosPublicados.setMaximumSize(new java.awt.Dimension(1197, 346));
        scrollpaneAnunciosPublicados.setMinimumSize(new java.awt.Dimension(1197, 346));
        scrollpaneAnunciosPublicados.setPreferredSize(new java.awt.Dimension(1197, 346));

        tableAnunciosPublicados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título", "Vagas Disponíveis", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableAnunciosPublicados.setMaximumSize(new java.awt.Dimension(1197, 347));
        tableAnunciosPublicados.setMinimumSize(new java.awt.Dimension(1197, 347));
        tableAnunciosPublicados.setPreferredSize(new java.awt.Dimension(1197, 347));
        tableAnunciosPublicados.setRowHeight(30);
        scrollpaneAnunciosPublicados.setViewportView(tableAnunciosPublicados);

        btnPesquisarAnunciosPublicados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa_16x16.png"))); // NOI18N
        btnPesquisarAnunciosPublicados.setText("Pesquisar");

        lblFiltroTituloAnunciosPublicados.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblFiltroTituloAnunciosPublicados.setText("Título:");

        btnEditarAnuncio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar_usuario_16x16.png"))); // NOI18N
        btnEditarAnuncio.setText("Editar");

        btnExcluirAnuncio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar_16x16.png"))); // NOI18N
        btnExcluirAnuncio.setText("Excluir");

        btnFiltroVoluntarios1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agenda_16x16.png"))); // NOI18N
        btnFiltroVoluntarios1.setText("Gerar Relatório");

        javax.swing.GroupLayout panelAnunciosPublicadosLayout = new javax.swing.GroupLayout(panelAnunciosPublicados);
        panelAnunciosPublicados.setLayout(panelAnunciosPublicadosLayout);
        panelAnunciosPublicadosLayout.setHorizontalGroup(
            panelAnunciosPublicadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnunciosPublicadosLayout.createSequentialGroup()
                .addComponent(lblFiltroTituloAnunciosPublicados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFiltroTituloAnunciosPublicados, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisarAnunciosPublicados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFiltroVoluntarios1)
                .addGap(18, 18, 18)
                .addComponent(btnEditarAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluirAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(scrollpaneAnunciosPublicados, javax.swing.GroupLayout.PREFERRED_SIZE, 1185, Short.MAX_VALUE)
        );
        panelAnunciosPublicadosLayout.setVerticalGroup(
            panelAnunciosPublicadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAnunciosPublicadosLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelAnunciosPublicadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFiltroVoluntarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAnunciosPublicadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelAnunciosPublicadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditarAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluirAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAnunciosPublicadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFiltroTituloAnunciosPublicados)
                            .addComponent(txtFiltroTituloAnunciosPublicados, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisarAnunciosPublicados, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollpaneAnunciosPublicados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCadAnuncio.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Anuncios"));
        panelCadAnuncio.setMaximumSize(new java.awt.Dimension(1197, 240));
        panelCadAnuncio.setMinimumSize(new java.awt.Dimension(1197, 240));
        panelCadAnuncio.setPreferredSize(new java.awt.Dimension(1197, 240));

        lblTituloCadAnuncio.setText("Título:");

        lblVagasCadAnuncio.setText("Vagas:");

        lblDescricaoCadAnuncio.setText("Descrição:");

        atxtDescricaoCadAnuncio.setColumns(20);
        atxtDescricaoCadAnuncio.setRows(5);
        scrollpaneDescricaoCadAnuncio.setViewportView(atxtDescricaoCadAnuncio);

        btnSalvarCadAnuncio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salvar_16x16.png"))); // NOI18N
        btnSalvarCadAnuncio.setText("Salvar");

        lblTipoServicoAnuncio.setText("Tipo de Serviço:");

        cmbTipoServicoAnuncio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelCadAnuncioLayout = new javax.swing.GroupLayout(panelCadAnuncio);
        panelCadAnuncio.setLayout(panelCadAnuncioLayout);
        panelCadAnuncioLayout.setHorizontalGroup(
            panelCadAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadAnuncioLayout.createSequentialGroup()
                .addGroup(panelCadAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCadAnuncioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvarCadAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCadAnuncioLayout.createSequentialGroup()
                        .addGroup(panelCadAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTituloCadAnuncio)
                            .addComponent(lblDescricaoCadAnuncio)
                            .addComponent(lblVagasCadAnuncio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCadAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollpaneDescricaoCadAnuncio)
                            .addComponent(txtTituloCadAnuncio)
                            .addGroup(panelCadAnuncioLayout.createSequentialGroup()
                                .addComponent(spinnerVagasCadAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTipoServicoAnuncio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbTipoServicoAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 81, Short.MAX_VALUE)))))
                .addGap(687, 687, 687))
        );
        panelCadAnuncioLayout.setVerticalGroup(
            panelCadAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadAnuncioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCadAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloCadAnuncio)
                    .addComponent(txtTituloCadAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCadAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbTipoServicoAnuncio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCadAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblVagasCadAnuncio)
                        .addComponent(spinnerVagasCadAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTipoServicoAnuncio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCadAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescricaoCadAnuncio)
                    .addComponent(scrollpaneDescricaoCadAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvarCadAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout panelAnuncioLayout = new javax.swing.GroupLayout(panelAnuncio);
        panelAnuncio.setLayout(panelAnuncioLayout);
        panelAnuncioLayout.setHorizontalGroup(
            panelAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnuncioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCadAnuncio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAnunciosPublicados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        panelAnuncioLayout.setVerticalGroup(
            panelAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnuncioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCadAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAnunciosPublicados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        menuPrincipalInstituicao.addTab("Anúncio", new javax.swing.ImageIcon(getClass().getResource("/img/aviso_16x16.png")), panelAnuncio); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPrincipalInstituicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPrincipalInstituicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        menuPrincipalInstituicao.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalInstituicaoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalInstituicaoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalInstituicaoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalInstituicaoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalInstituicaoUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextArea atxtDescricaoCadAnuncio;
    private javax.swing.JTextArea atxtDescricaoCadAviso;
    private javax.swing.JTextArea atxtObservacoes;
    private javax.swing.JButton btnEditarAnuncio;
    private javax.swing.JButton btnEditarAviso;
    private javax.swing.JButton btnEditarDadosInstituicao1;
    private javax.swing.JButton btnExcluirAnuncio;
    private javax.swing.JButton btnExcluirAviso;
    private javax.swing.JButton btnFiltroVoluntarios;
    private javax.swing.JButton btnFiltroVoluntarios1;
    private javax.swing.JButton btnPesquisarAnunciosPublicados;
    private javax.swing.JButton btnPesquisarAvisosPublicados;
    private javax.swing.JButton btnPesquisarFiltroVoluntarios;
    private javax.swing.JButton btnSalvarAvisoCadAviso;
    private javax.swing.JButton btnSalvarCadAnuncio;
    private javax.swing.JButton btnSalvarDadosInstituicao;
    private javax.swing.JComboBox cmbTipoServicoAnuncio;
    private javax.swing.JComboBox cmbTipoServicoAviso;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblDescricaoCadAnuncio;
    private javax.swing.JLabel lblDescricaoCadAviso;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailFiltroVoluntarios;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblFiltroTituloAnunciosPublicados;
    private javax.swing.JLabel lblFiltroTituloAvisosPublicados;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeFiltroVoluntarios;
    private javax.swing.JLabel lblObservacoes;
    private javax.swing.JLabel lblRazaoSocial;
    private javax.swing.JLabel lblResponsavel;
    private javax.swing.JLabel lblSite;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTipoServicoAnuncio;
    private javax.swing.JLabel lblTipoServicoAviso;
    private javax.swing.JLabel lblTituloCadAnuncio;
    private javax.swing.JLabel lblTituloCadAviso;
    private javax.swing.JLabel lblVagasCadAnuncio;
    private javax.swing.JTabbedPane menuPrincipalInstituicao;
    private javax.swing.JPanel panelAnuncio;
    private javax.swing.JPanel panelAnunciosPublicados;
    private javax.swing.JPanel panelAviso;
    private javax.swing.JPanel panelAvisosPublicados;
    private javax.swing.JPanel panelCadAnuncio;
    private javax.swing.JPanel panelCadAviso;
    private javax.swing.JPanel panelDadosInstituicao;
    private javax.swing.JPanel panelFiltroVoluntarios;
    private javax.swing.JPanel panelInstituicao;
    private javax.swing.JPanel panelVoluntarios;
    private javax.swing.JScrollPane scrollpaneAnunciosPublicados;
    private javax.swing.JScrollPane scrollpaneAvisosPublicados;
    private javax.swing.JScrollPane scrollpaneDescricaoCadAnuncio;
    private javax.swing.JScrollPane scrollpaneDescricaoCadAviso;
    private javax.swing.JScrollPane scrollpaneObservacoes;
    private javax.swing.JScrollPane scrollpaneVoluntarios;
    private javax.swing.JSpinner spinnerVagasCadAnuncio;
    private javax.swing.JTable tableAnunciosPublicados;
    private javax.swing.JTable tableAvisosPublicados;
    private javax.swing.JTable tableVoluntarios;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmailFiltroVoluntarios;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtFiltroTituloAnunciosPublicados;
    private javax.swing.JTextField txtFiltroTituloAvisosPublicados;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeFiltroVoluntarios;
    private javax.swing.JTextField txtRazaoSocial;
    private javax.swing.JTextField txtResponsavel;
    private javax.swing.JTextField txtSite;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtTituloCadAnuncio;
    private javax.swing.JTextField txtTituloCadAviso;
    // End of variables declaration                   
}
