/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.sc.ajudeaqui.view;

/**
 *
 * @author Jaime Gomes
 */
public class RegistroUI extends javax.swing.JInternalFrame {

	// Variables declaration - do not modify
	private static final long serialVersionUID = 1L;
	private javax.swing.JButton btnCancelar;
	private javax.swing.JButton btnSalvar;
	@SuppressWarnings("rawtypes")
	private javax.swing.JComboBox cmbTipo;
	private javax.swing.JLabel lblConfirmarSenha;
	private javax.swing.JLabel lblLembreteSenha;
	private javax.swing.JLabel lblLogin;
	private javax.swing.JLabel lblSenha;
	private javax.swing.JLabel lblTipo;
	private javax.swing.JPanel panelFormCadastro;
	private javax.swing.JTextField txtConfirmarSenha;
	private javax.swing.JTextField txtLembreteSenha;
	private javax.swing.JTextField txtLogin;
	private javax.swing.JTextField txtSenha;
	// End of variables declaration

	/**
	 * Creates new form RegistroUI
	 */
	public RegistroUI() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings({ "unchecked", "rawtypes" })
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		panelFormCadastro = new javax.swing.JPanel();
		lblLogin = new javax.swing.JLabel();
		lblSenha = new javax.swing.JLabel();
		lblTipo = new javax.swing.JLabel();
		lblConfirmarSenha = new javax.swing.JLabel();
		txtLogin = new javax.swing.JTextField();
		txtSenha = new javax.swing.JTextField();
		txtConfirmarSenha = new javax.swing.JTextField();
		cmbTipo = new javax.swing.JComboBox();
		lblLembreteSenha = new javax.swing.JLabel();
		txtLembreteSenha = new javax.swing.JTextField();
		btnCancelar = new javax.swing.JButton();
		btnSalvar = new javax.swing.JButton();

		setTitle("Cadastro de Usuários");

		panelFormCadastro.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Formulário de Cadastro"));

		lblLogin.setText("Login:");

		lblSenha.setText("Senha:");

		lblTipo.setText("Tipo:");

		lblConfirmarSenha.setText("Confirmar Senha:");

		cmbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"...", "Voluntário", "Instituição" }));

		lblLembreteSenha.setText("Lembrete Senha:");

		javax.swing.GroupLayout panelFormCadastroLayout = new javax.swing.GroupLayout(
				panelFormCadastro);
		panelFormCadastro.setLayout(panelFormCadastroLayout);
		panelFormCadastroLayout
				.setHorizontalGroup(panelFormCadastroLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								panelFormCadastroLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												panelFormCadastroLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																panelFormCadastroLayout
																		.createSequentialGroup()
																		.addComponent(
																				lblTipo)
																		.addGap(62,
																				62,
																				62)
																		.addComponent(
																				cmbTipo,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				137,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																panelFormCadastroLayout
																		.createSequentialGroup()
																		.addComponent(
																				lblLembreteSenha)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				txtLembreteSenha,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				256,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																panelFormCadastroLayout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				false)
																		.addGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				panelFormCadastroLayout
																						.createSequentialGroup()
																						.addComponent(
																								lblLogin)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								txtLogin,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								141,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				panelFormCadastroLayout
																						.createSequentialGroup()
																						.addGroup(
																								panelFormCadastroLayout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																										.addComponent(
																												lblConfirmarSenha)
																										.addComponent(
																												lblSenha))
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addGroup(
																								panelFormCadastroLayout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																										.addComponent(
																												txtSenha,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												142,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addComponent(
																												txtConfirmarSenha,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												142,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))))
										.addContainerGap(34, Short.MAX_VALUE)));
		panelFormCadastroLayout
				.setVerticalGroup(panelFormCadastroLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								panelFormCadastroLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												panelFormCadastroLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(lblLogin)
														.addComponent(
																txtLogin,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																19,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												panelFormCadastroLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(lblSenha)
														.addComponent(
																txtSenha,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																19,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												panelFormCadastroLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																lblConfirmarSenha)
														.addComponent(
																txtConfirmarSenha,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																19,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												panelFormCadastroLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(lblTipo)
														.addComponent(
																cmbTipo,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																19,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												panelFormCadastroLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																lblLembreteSenha)
														.addComponent(
																txtLembreteSenha,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"../img/cancelar_16x16.png"))); // NOI18N
		btnCancelar.setText("Cancelar");

		btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"../img/next_16x16.png"))); // NOI18N
		btnSalvar.setText("Avançar");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														panelFormCadastro,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGap(0,
																		0,
																		Short.MAX_VALUE)
																.addComponent(
																		btnSalvar,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		116,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		btnCancelar,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		116,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(panelFormCadastro,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														btnSalvar,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														19,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														btnCancelar,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														19,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

}
