/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.sc.ajudeaqui.view;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import br.senai.sc.ajudeaqui.abstracts.Entidade;
import br.senai.sc.ajudeaqui.model.Anuncio;
import br.senai.sc.ajudeaqui.model.Voluntario;

/**
 *
 * @author Jaime Gomes
 */
public class RelatorioUI extends javax.swing.JInternalFrame {

	// Variables declaration - do not modify
	private static final long serialVersionUID = 1L;
	private javax.swing.JButton btnFechar;
	private javax.swing.JLabel lblTitulo;
	private javax.swing.JPanel panelRelatorio;
	private javax.swing.JScrollPane scrollPaneTabel;
	private javax.swing.JTable table;
	// End of variables declaration

	private Voluntario voluntario = null;
	private Anuncio anuncio = null;

	/**
	 * Creates new form RelatorioUI
	 */
	public RelatorioUI(Entidade entidade) {
		initComponents(entidade);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	private void initComponents(Entidade entidade) {

		String titulo = "";

		if (entidade instanceof Voluntario) {
			voluntario = (Voluntario) entidade;
			titulo = "Voluntários";

		} else if (entidade instanceof Anuncio) {
			anuncio = (Anuncio) entidade;
			titulo = "Vagas";
		}

		panelRelatorio = new javax.swing.JPanel();
		lblTitulo = new javax.swing.JLabel();
		scrollPaneTabel = new javax.swing.JScrollPane();
		table = new javax.swing.JTable();
		btnFechar = new javax.swing.JButton();

		setTitle(":: Sistema do Voluntário Ajude Aqui ::");

		lblTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
		lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lblTitulo.setText("Relatório " + titulo + " Disponíveis");

		if (voluntario != null) {
			// table.setModel(new VoluntarioTableModel(list));

		} else {
			// table.setModel(new AnuncioTableModel(list));
		}

		// double click na tabela
		table.addMouseListener(new MouseAdapter() {

			@Override
			public void mouseClicked(MouseEvent e) {
				if (e.getClickCount() == 2) {

					if (voluntario != null) {
						// abre tela com os dados do perfil do voluntario
					} else if (anuncio != null) {
						// abre tela com os dados do anuncio publicado
					}

				}
			}
		});
		scrollPaneTabel.setViewportView(table);

		btnFechar.setIcon(new javax.swing.ImageIcon("img/cancelar_16x16.png")); // NOI18N
		btnFechar.setText("Fechar");

		javax.swing.GroupLayout gl_panelRelatorio = new javax.swing.GroupLayout(
				panelRelatorio);
		panelRelatorio.setLayout(gl_panelRelatorio);
		gl_panelRelatorio
				.setHorizontalGroup(gl_panelRelatorio
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(lblTitulo,
								javax.swing.GroupLayout.Alignment.TRAILING,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.addGroup(
								gl_panelRelatorio
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												scrollPaneTabel,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												772, Short.MAX_VALUE)
										.addContainerGap()));
		gl_panelRelatorio
				.setVerticalGroup(gl_panelRelatorio
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								gl_panelRelatorio
										.createSequentialGroup()
										.addComponent(
												lblTitulo,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												73,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(scrollPaneTabel)
										.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(panelRelatorio,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE).addContainerGap())
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(btnFechar,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										93,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(19, 19, 19)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(panelRelatorio,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(btnFechar,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										19,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));

		pack();
	}// </editor-fold>

}
