/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.sc.ajudeaqui.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import br.senai.sc.ajudeaqui.abstracts.Entidade;
import br.senai.sc.ajudeaqui.controller.AnuncioController;
import br.senai.sc.ajudeaqui.controller.VoluntarioController;
import br.senai.sc.ajudeaqui.model.Anuncio;
import br.senai.sc.ajudeaqui.model.Instituicao;
import br.senai.sc.ajudeaqui.model.Voluntario;
import br.senai.sc.ajudeaqui.tablemodel.AnuncioTableModel;
import br.senai.sc.ajudeaqui.tablemodel.VoluntarioTableModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author Jaime Gomes
 */
public class RelatorioUI extends javax.swing.JInternalFrame {

	// Variables declaration - do not modify
	private static final long serialVersionUID = 1L;
	private javax.swing.JButton btnFechar;
	private javax.swing.JLabel lblTitulo;
	private javax.swing.JPanel panelRelatorio;
	private javax.swing.JScrollPane scrollPaneTabel;
	private javax.swing.JTable table;
	// End of variables declaration

	private Voluntario voluntario = null;
	private Anuncio anuncio = null;
	private VoluntarioController voluntarioController = null;
	private AnuncioController anuncioController = null;

	/**
	 * Creates new form RelatorioUI
	 */
	public RelatorioUI(String flag, Entidade entidade) {
		initComponents(flag, entidade);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	private void initComponents(String flag, Entidade entidade) {

		String titulo = "";

		if (flag.equals("Voluntario")) {
			titulo = "Voluntários";

		} else if (flag.equals("Anuncio")) {
			titulo = "Vagas";
		}

		panelRelatorio = new javax.swing.JPanel();
		lblTitulo = new javax.swing.JLabel();
		scrollPaneTabel = new javax.swing.JScrollPane();
		table = new javax.swing.JTable();
		btnFechar = new javax.swing.JButton();

		setTitle(":: Sistema do Voluntário Ajude Aqui ::");

		lblTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
		lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lblTitulo.setText("Relatório " + titulo + " Disponíveis");

		if (voluntario != null) {

			voluntarioController = new VoluntarioController();

			try {
				table.setModel(new VoluntarioTableModel(voluntarioController.listar()));
			} catch (Exception e1) {
				e1.printStackTrace();
			}

		} else {

			anuncioController = new AnuncioController();

			try {
				Instituicao inst = (Instituicao) entidade;
				table.setModel(new AnuncioTableModel(anuncioController.getPorIdInstituicao(inst.getId())));
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}

		// double click na tabela
		table.addMouseListener(new MouseAdapter() {

			@Override
			public void mouseClicked(MouseEvent e) {
				if (e.getClickCount() == 2) {

					if (voluntario != null) {
						// abre tela com os dados do perfil do voluntario
					} else if (anuncio != null) {
						// abre tela com os dados do anuncio publicado
					}

				}
			}
		});
		scrollPaneTabel.setViewportView(table);

		btnFechar.setIcon(new javax.swing.ImageIcon("img/cancelar_16x16.png")); // NOI18N
		btnFechar.setText("Fechar");
		btnFechar.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				dispose();
				
			}
		});

		javax.swing.GroupLayout gl_panelRelatorio = new javax.swing.GroupLayout(panelRelatorio);
		panelRelatorio.setLayout(gl_panelRelatorio);
		gl_panelRelatorio.setHorizontalGroup(gl_panelRelatorio
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addGroup(gl_panelRelatorio.createSequentialGroup().addContainerGap()
						.addComponent(scrollPaneTabel, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
						.addContainerGap()));
		gl_panelRelatorio
				.setVerticalGroup(gl_panelRelatorio.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(gl_panelRelatorio.createSequentialGroup()
								.addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 73,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(scrollPaneTabel).addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
							.addComponent(panelRelatorio, GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
							.addContainerGap())
						.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
							.addComponent(btnFechar, GroupLayout.PREFERRED_SIZE, 93, GroupLayout.PREFERRED_SIZE)
							.addGap(20))))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(panelRelatorio, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(btnFechar, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(28, Short.MAX_VALUE))
		);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>

}
