package br.senai.sc.ajudeaqui.view;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import javax.swing.border.TitledBorder;

import br.senai.sc.ajudeaqui.abstracts.Entidade;
import br.senai.sc.ajudeaqui.controller.FuncaoController;
import br.senai.sc.ajudeaqui.controller.FuncaoVoluntarioController;
import br.senai.sc.ajudeaqui.controller.HorarioController;
import br.senai.sc.ajudeaqui.controller.HorarioVoluntarioController;
import br.senai.sc.ajudeaqui.model.Funcao;
import br.senai.sc.ajudeaqui.model.FuncaoVoluntario;
import br.senai.sc.ajudeaqui.model.Horario;
import br.senai.sc.ajudeaqui.model.HorarioVoluntario;
import br.senai.sc.ajudeaqui.model.Voluntario;
import br.senai.sc.ajudeaqui.utils.StringUtils;

public class VoluntarioUI extends javax.swing.JInternalFrame {

	private static final long serialVersionUID = 1L;
	private javax.swing.JButton btnFechar;
	private javax.swing.JLabel lblNomeDinamico;
	private javax.swing.JPanel panelAnuncio;
	private JLabel lblTelefone;
	private JLabel lblNrTelefone;
	private JLabel lblCpf;
	private JLabel lblNrCpf;
	private JLabel lblEmail;
	private JLabel lblEmailDinamico;
	private JLabel lblEndereco;
	private JLabel lblEnderecoDinamico;
	private JLabel lblSexo;
	private JLabel lblSexoDinamico;
	private JLabel lblEstadoCivil;
	private JLabel lblEstadoCivilDinamico;
	private JLabel lblComplemento;
	private JLabel lblComplementoDinamico;
	private JLabel lblCelular;
	private JLabel lblCelularDianamico;
	private JLabel lblInformaesComplementares;
	private JLabel lblInfoComplementarDinamico;
	private JLabel lblDataNascimento;
	private JLabel lblDataNascDinamico;
	private JPanel panel;
	private JLabel lblHorariosDisponiveisDinamico;
	private JLabel lblTipoDeServico;
	private JLabel lblTipoServicoDinamico;

	private FuncaoVoluntarioController funcaoVoluntarioController = new FuncaoVoluntarioController();
	private HorarioVoluntarioController horarioVoluntarioController = new HorarioVoluntarioController();

	private FuncaoController funcaoController = new FuncaoController();
	private HorarioController horarioController = new HorarioController();

	/**
	 * Creates new form RelatorioUI
	 */
	public VoluntarioUI(Voluntario voluntario) {
		initComponents(voluntario);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	private void initComponents(final Voluntario voluntario) {

		panelAnuncio = new javax.swing.JPanel();
		btnFechar = new javax.swing.JButton();
		btnFechar.setIcon(new javax.swing.ImageIcon("img/cancelar_16x16.png")); // NOI18N
		btnFechar.setText("Fechar");
		btnFechar.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				dispose();

			}
		});

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle(":: Sistema do Voluntário Ajude Aqui ::");
		setResizable(false);

		panel = new JPanel();
		panel.setBorder(
				new TitledBorder(null, "Dados do Volunt\u00E1rio", TitledBorder.LEADING, TitledBorder.TOP, null, null));
		lblNomeDinamico = new javax.swing.JLabel(voluntario.getNome());

		lblNomeDinamico.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
		lblNomeDinamico.setHorizontalAlignment(SwingConstants.LEFT);

		JLabel lblNome = new JLabel("Nome:");
		lblNome.setHorizontalAlignment(SwingConstants.CENTER);
		lblNome.setFont(new Font("Dialog", Font.BOLD, 36));

		javax.swing.GroupLayout gl_panelAnuncio = new javax.swing.GroupLayout(panelAnuncio);
		gl_panelAnuncio
				.setHorizontalGroup(gl_panelAnuncio.createParallelGroup(Alignment.LEADING)
						.addGroup(gl_panelAnuncio.createSequentialGroup().addContainerGap()
								.addGroup(gl_panelAnuncio.createParallelGroup(Alignment.LEADING)
										.addComponent(panel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
								.addGroup(gl_panelAnuncio.createSequentialGroup()
										.addComponent(lblNome, GroupLayout.PREFERRED_SIZE, 145,
												GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.UNRELATED)
										.addComponent(lblNomeDinamico, GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)))
						.addContainerGap()));
		gl_panelAnuncio
				.setVerticalGroup(gl_panelAnuncio.createParallelGroup(Alignment.LEADING)
						.addGroup(gl_panelAnuncio.createSequentialGroup().addContainerGap()
								.addGroup(gl_panelAnuncio.createParallelGroup(Alignment.BASELINE)
										.addComponent(lblNome, GroupLayout.PREFERRED_SIZE, 43,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(lblNomeDinamico))
								.addPreferredGap(ComponentPlacement.RELATED)
								.addComponent(panel, GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE).addGap(30)));
		panel.setLayout(null);
		lblCpf = new JLabel("CPF:");
		lblCpf.setBounds(12, 30, 31, 15);
		panel.add(lblCpf);
		lblNrCpf = new JLabel(voluntario.getCpf());
		lblNrCpf.setBounds(233, 30, 152, 15);
		panel.add(lblNrCpf);
		lblTelefone = new JLabel("Telefone:");
		lblTelefone.setBounds(12, 57, 67, 15);
		panel.add(lblTelefone);
		lblNrTelefone = new JLabel(voluntario.getTelefone());
		lblNrTelefone.setBounds(233, 57, 176, 15);
		panel.add(lblNrTelefone);
		lblDataNascimento = new JLabel("Data Nascimento:");
		lblDataNascimento.setBounds(12, 84, 126, 15);
		panel.add(lblDataNascimento);
		try {
			lblDataNascDinamico = new JLabel(
					StringUtils.getInstance().parseDateToString(voluntario.getDataNascimento()));
		} catch (ParseException e1) {
			e1.printStackTrace();
		}
		lblDataNascDinamico.setBounds(233, 84, 152, 15);
		panel.add(lblDataNascDinamico);
		lblEndereco = new JLabel("Endere\u00E7o:");
		lblEndereco.setBounds(12, 111, 71, 15);
		panel.add(lblEndereco);

		lblEnderecoDinamico = new JLabel(voluntario.getEndereco());
		lblEnderecoDinamico.setBounds(233, 111, 457, 15);
		panel.add(lblEnderecoDinamico);
		lblComplemento = new JLabel("Complemento:");
		lblComplemento.setBounds(12, 138, 102, 15);
		panel.add(lblComplemento);
		lblComplementoDinamico = new JLabel(voluntario.getComplemento());
		lblComplementoDinamico.setBounds(233, 138, 78, 15);
		panel.add(lblComplementoDinamico);
		lblEmail = new JLabel("Email:");
		lblEmail.setBounds(12, 165, 42, 15);
		panel.add(lblEmail);
		lblEmailDinamico = new JLabel(voluntario.getEmail());
		lblEmailDinamico.setBounds(233, 165, 392, 15);
		panel.add(lblEmailDinamico);
		lblSexo = new JLabel("Sexo:");
		lblSexo.setBounds(12, 219, 39, 15);
		panel.add(lblSexo);
		lblSexoDinamico = new JLabel(voluntario.getSexo());
		lblSexoDinamico.setBounds(233, 219, 152, 15);
		panel.add(lblSexoDinamico);
		lblEstadoCivil = new JLabel("Estado Civil:");
		lblEstadoCivil.setBounds(12, 246, 86, 15);
		panel.add(lblEstadoCivil);
		lblEstadoCivilDinamico = new JLabel(voluntario.getEstadoCivil());
		lblEstadoCivilDinamico.setBounds(233, 246, 152, 15);
		panel.add(lblEstadoCivilDinamico);
		lblCelular = new JLabel("Celular:");
		lblCelular.setBounds(12, 192, 55, 15);
		panel.add(lblCelular);
		lblCelularDianamico = new JLabel(voluntario.getCelular());
		lblCelularDianamico.setBounds(233, 192, 196, 15);
		panel.add(lblCelularDianamico);
		lblInformaesComplementares = new JLabel("Informa\u00E7\u00F5es Complementares:");
		lblInformaesComplementares.setBounds(12, 273, 216, 15);
		panel.add(lblInformaesComplementares);
		lblInfoComplementarDinamico = new JLabel(voluntario.getInformacoesComplementares());
		lblInfoComplementarDinamico.setBounds(233, 273, 451, 15);
		panel.add(lblInfoComplementarDinamico);

		JLabel lblHorariosDisponiveis = new JLabel("Hor\u00E1rios Dispon\u00EDveis:");
		lblHorariosDisponiveis.setBounds(12, 299, 146, 14);
		panel.add(lblHorariosDisponiveis);

		lblHorariosDisponiveisDinamico = new JLabel("");
		lblHorariosDisponiveisDinamico.setBounds(233, 299, 457, 14);

		StringBuilder horarios = new StringBuilder();

		try {
			for (Entidade e : horarioVoluntarioController.getListPorIdVoluntario(voluntario.getId())) {
				HorarioVoluntario horarioVoluntario = (HorarioVoluntario) e;

				Horario horario = (Horario) horarioController.getPorId(horarioVoluntario.getHorario().getId());

				horarios.append("" + horario.getHorario() + ", ");

			}

			lblHorariosDisponiveisDinamico.setText(horarios.substring(0, horarios.length() - 2));

		} catch (Exception e1) {
			e1.printStackTrace();
		}

		panel.add(lblHorariosDisponiveisDinamico);

		lblTipoDeServico = new JLabel("Tipo de Servi\u00E7o:");
		lblTipoDeServico.setBounds(12, 324, 146, 14);
		panel.add(lblTipoDeServico);

		lblTipoServicoDinamico = new JLabel("");
		lblTipoServicoDinamico.setBounds(233, 324, 457, 14);

		StringBuilder funcoes = new StringBuilder();

		try {
			for (Entidade e : funcaoVoluntarioController.getListPorIdVoluntario(voluntario.getId())) {
				FuncaoVoluntario funcaoVoluntario = (FuncaoVoluntario) e;

				Funcao funcao = (Funcao) funcaoController.getPorId(funcaoVoluntario.getFuncao().getId());

				funcoes.append("" + funcao.getFuncao() + ", ");

			}

			lblTipoServicoDinamico.setText(funcoes.substring(0, funcoes.length() - 2));

		} catch (Exception e1) {
			e1.printStackTrace();
		}

		panel.add(lblTipoServicoDinamico);
		panelAnuncio.setLayout(gl_panelAnuncio);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(panelAnuncio, GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
								.addComponent(btnFechar, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE))
				.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(panelAnuncio, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(btnFechar, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
						.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>
}
